"use client";

import Link from "next/link";
import { ArrowRight, CircleDollarSign, CookingPot, PackageCheck, Refrigerator, ShoppingBasket, Sparkles } from "lucide-react";
import { usePantry } from "@/lib/data/provider";
import { calculateRisk } from "@/lib/risk";

export default function RecommendationsPage(){
 const {items}=usePantry(); const available=items.filter((item)=>item.status==="available"); const ranked=available.map((item)=>({item,risk:calculateRisk(item)})).sort((a,b)=>b.risk.score-a.risk.score); const top=ranked[0]?.item; const freezer=available.find((item)=>item.storageLocation!=="Freezer"&&["Meat","Bread & Bakery"].includes(item.category)); const duplicate=available.find((item,index)=>available.findIndex((other)=>other.productName.toLowerCase()===item.productName.toLowerCase())!==index); const ingredients=available.filter((item)=>["Tomatoes","Chicken","Rice"].includes(item.productName)).map((item)=>item.productName);
 const cards=[
   {icon:PackageCheck,tone:"red",label:"Use today",title:top?`${top.productName} needs attention first.`:"No urgent items today.",text:top?"Its expiry and item condition create the highest current planning risk.":"Your available items currently have enough time remaining.",action:"Open pantry",href:"/pantry"},
   {icon:Refrigerator,tone:"blue",label:"Storage action",title:freezer?`Consider freezing ${freezer.productName.toLowerCase()}.`:"Freezer planning looks good.",text:freezer?"Freezing can extend useful storage when the product will not be used soon.":"No obvious freezer action was found.",action:"Review item",href:"/pantry"},
   {icon:ShoppingBasket,tone:"amber",label:"Avoid duplicates",title:duplicate?`You already have more than one ${duplicate.productName.toLowerCase()} entry.`:"No duplicate product found.",text:duplicate?"Check your pantry before adding this product to the next shopping trip.":"Your current inventory has no obvious duplicate names.",action:"Shopping list",href:"/shopping-list"},
   {icon:CookingPot,tone:"green",label:"Meal combination",title:ingredients.length>=2?`${ingredients.join(" + ")} can be used together.`:"Build a meal around your most urgent items.",text:"Keep recommendations simple and based on available products, not generated safety advice.",action:"See use-first list",href:"/dashboard"},
 ];
 return <div className="page-stack"><section className="page-heading-row"><div><p className="eyebrow">Rule-based guidance</p><h1>Smart Recommendations</h1><p>Simple actions based on expiry, quantity, storage, and duplicate products.</p></div></section><section className="recommendation-layout"><div className="recommendation-grid">{cards.map(({icon:Icon,tone,label,title,text,action,href})=><article className="recommendation-card" key={label}><span className={`recommendation-icon ${tone}`}><Icon/></span><div><p className="eyebrow">{label}</p><h2>{title}</h2><p>{text}</p><Link href={href}>{action}<ArrowRight size={15}/></Link></div></article>)}</div><aside className="savings-panel"><span className="savings-spark"><Sparkles/></span><p className="eyebrow">Household progress</p><h2>Small actions add up.</h2><dl><div><dt>Estimated saved this month</dt><dd>PKR 3,250</dd></div><div><dt>Food waste change</dt><dd>18% lower</dd></div><div><dt>Items rescued before expiry</dt><dd>7</dd></div></dl><div className="progress-ring"><CircleDollarSign/><div><strong>82</strong><span>efficiency score</span></div></div><p className="explain-note"><strong>Why am I seeing this?</strong> Recommendations use only the information recorded in your pantry. They are planning suggestions, not food-safety determinations.</p></aside></section></div>;
}
