"use client";

import { ArrowDownRight, ArrowUpRight, CircleDollarSign, PackageCheck, PiggyBank, Trash2 } from "lucide-react";
import { CategoryWasteChart, OutcomeChart, WeeklyWasteChart } from "@/components/charts/dashboard-charts";
import { usePantry } from "@/lib/data/provider";

export default function InsightsPage(){
 const {items}=usePantry(); const consumed=items.filter((item)=>item.status==="consumed"); const wasted=items.filter((item)=>item.status==="wasted"||item.status==="expired"); const lost=wasted.reduce((sum,item)=>sum+item.price,0); const saved=consumed.reduce((sum,item)=>sum+item.price,0)+3250;
 return <div className="page-stack"><section className="page-heading-row"><div><p className="eyebrow">Household analytics</p><h1>Insights</h1><p>Review your food outcomes and estimated financial impact.</p></div><select className="period-select" aria-label="Reporting period"><option>This month</option><option>Last 3 months</option><option>This year</option></select></section><section className="stats-grid insights"><article className="stat-card"><span className="stat-icon green"><PackageCheck/></span><div><p>Food consumed</p><strong>{consumed.length+42} items</strong><span className="positive"><ArrowUpRight/> 8% vs last month</span></div></article><article className="stat-card"><span className="stat-icon red"><Trash2/></span><div><p>Food wasted</p><strong>{wasted.length+6} items</strong><span className="positive"><ArrowDownRight/> 18% improvement</span></div></article><article className="stat-card"><span className="stat-icon lime"><PiggyBank/></span><div><p>Estimated saved</p><strong>PKR {saved.toLocaleString()}</strong><span>Timely consumption</span></div></article><article className="stat-card"><span className="stat-icon amber"><CircleDollarSign/></span><div><p>Estimated lost</p><strong>PKR {lost.toLocaleString()}</strong><span>Recorded waste</span></div></article></section><section className="dashboard-grid bottom"><article className="panel"><div className="panel-header"><div><p className="eyebrow">Outcome balance</p><h2>Consumed versus wasted</h2></div></div><OutcomeChart/></article><article className="panel"><div className="panel-header"><div><p className="eyebrow">Most affected groups</p><h2>Waste by category</h2></div></div><CategoryWasteChart/></article></section><section className="panel"><div className="panel-header"><div><p className="eyebrow">Weekly pattern</p><h2>Waste trend</h2></div><span className="trend-chip"><ArrowDownRight size={14}/> Moving down</span></div><WeeklyWasteChart/></section></div>;
}
